name: deploy-test
on: 
  push:
    branches: 'main'
jobs:
  build-and-deploy-to-lambda:
    runs-on: ubuntu-latest
    env:
      AWS_DEPLOY_ACCESS_KEY: ${{secrets.AWS_DEPLOY_ACCESS_KEY}}
      AWS_DEPLOY_ACCESS_SECRET: ${{secrets.AWS_DEPLOY_ACCESS_SECRET}}
      AWS_DEPLOY_REGION: eu-west-2
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with: 
          dotnet-version: '3.1.x'
      - name: Run Tests
        run: dotnet test ./src
      - name: Install dotnet lambda
        run: dotnet tool install -g Amazon.Lambda.Tools && export PATH="$PATH:/root/.dotnet/tools"
      - name: Build & Deploy
        run: bash ./scripts/deploy-tl-xr.sh